<?php

return [
    'role_structure' => [
        'super' => [
            'dashboard' => 'v',
            'map' => 'v',
            'chart' => 'v',
            'admin' => 'v',
            'user' => 'c,r,u,d,s,v',
            'role' => 'c,r,u,d,s,v',
            'permission' => 'c,r,u,d,s,v',
            'team' => 'c,r,u,d,s,v',
            'activitylog' => 'r,d,v',
            'accesslog' => 'r,d,v',
            'securitylog' => 'r,d,v',
            'organization' => 'v',
            'company' => 'c,r,u,d,s,v',
            'department' => 'c,r,u,d,s,v',
            'location' => 'c,r,u,d,s,v',
            'employee' => 'c,r,u,d,s,v',
            'position' => 'c,r,u,d,s,v',
            'project' => 'c,r,u,d,s,v',
            'costcenter' => 'c,r,u,d,s,v',
            'accountcode' => 'c,r,u,d,s,v',
            'itemgroup' => 'c,r,u,d,s,v',
            'item' => 'c,r,u,d,s,v',
            'pr' => 'c,r,u,d,s,v,r,a,can,rej',
            'inventory' => 'c,r,u,d,s,v,adj',
        ],
        'admin' => [
            'dashboard' => 'v',
            'map' => 'v',
            'chart' => 'v',
            'admin' => 'v',
            'user' => 'c,r,u,d,s,v',
            'role' => 'c,r,u,d,s,v',
            'permission' => 'c,r,u,d,s,v',
            'team' => 'c,r,u,d,s,v',
            'activitylog' => 'r,d,v',
            'accesslog' => 'r,d,v',
            'securitylog' => 'r,d,v',
            'organization' => 'v',
            'company' => 'c,r,u,d,s,v',
            'department' => 'c,r,u,d,s,v',
            'location' => 'c,r,u,d,s,v',
            'employee' => 'c,r,u,d,s,v',
            'position' => 'c,r,u,d,s,v',
            'project' => 'c,r,u,d,s,v',
            'costcenter' => 'c,r,u,d,s,v',
            'accountcode' => 'c,r,u,d,s,v',
            'itemgroup' => 'c,r,u,d,s,v',
            'item' => 'c,r,u,d,s,v',
            'pr' => 'c,r,u,d,s,v,r,a,can,rej',
            'inventory' => 'c,r,u,d,s,v,adj',
        ],
        'user' => [
            'pr' => 'c,r,u,s,v,r,a',
            'inventory' => 'c,r,u,s,v',
        ],
    ],
    'permission_structure' => [
        'cru_user' => [
            'pr' => 'c,r,u'
        ],
    ],
    'permissions_map' => [
        'c' => 'create',
        'r' => 'read',
        'u' => 'update',
        'd' => 'delete',
        's' => 'restore',
        'v' => 'view',
        'r' => 'review',
        'a' => 'approval',
        'can' => 'cancel',
        'rej' => 'reject',
        'adj' => 'adjust',
    ]
];
